import { Rubik } from "next/font/google";
import Nabvar from "../components/Navbar";
import Footer from "../components/Footer";
import "./globals.css";
const inter =  Rubik({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={`${inter.className } antialiased`}>
      <Nabvar/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
